In [1]:
import requests as req 
from bs4 import BeautifulSoup as bs
import numpy as np 
import pandas as pd

In [2]:
html = req.get('https://www.worldometers.info/coronavirus/')

In [3]:
html_parsed = bs(html.content)

In [4]:
table = html_parsed.find('table', attrs = {'id': 'main_table_countries_today'})

In [5]:
table

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">TotÂ Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
<th width="30">New Cases/1M pop</th>
<th width="30">New Deaths/1M pop</th>
<th width="30">Active Cases/1M pop</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>95,695,615</td>
<td>+10,080</td>
<td>1,425,823</td>
<td>+239</td>
<td>68,721,845</td>
<td>+18,916</td>
<td>25,547,947</td>
<td>10,306</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>126,010,670</td>
<td>+478,842</td>
<td>1,372,245</td>
<td>+1,205</td>
<td>112,418,352</td>
<td>+178,143</td>
<td>12,220,073</td>
<td>29,036</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>55,223,002</td>
<td>+15,538</td>
<td>1,267,763</td>
<td>+95</td>
<td>49,921,606</td>
<td>+40,891</td>
<td>4,033,633</td>
<td>12,378</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>164,944,882</td>
<td>+384,229</td>
<td>1,738,979</td>
<td>+1,021</td>
<td>145,596,572</td>
<td>+484,992</td>
<td>17,609,331</td>
<td>11,997</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>11,629,014</td>
<td>+423</td>
<td>251,712</td>
<td>+15</td>
<td>10,779,614</td>
<td>+1,804</td>
<td>597,688</td>
<td>1,555</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>4,211,709</td>
<td>+43,982</td>
<td>8,256</td>
<td>+24</td>
<td>3,668,369</td>
<td>+23,589</td>
<td>535,084</td>
<td>159</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>706</td>
<td></td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>457,715,613</td>
<td>+933,094</td>
<td>6,064,793</td>
<td>+2,599</td>
<td>391,107,064</td>
<td>+748,335</td>
<td>60,543,756</td>
<td>65,431</td>
<td>58,721</td>
<td>778.1</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">81,171,036</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+1,502</td>
<td style="font-weight: bold; text-align:right;">993,719 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+26</td>
<td style="font-weight: bold; text-align:right">55,925,259</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+10,121</td>
<td style="text-align:right;font-weight:bold;">24,252,058</td>
<td style="font-weight: bold; text-align:right">4,390</td>
<td style="font-weight: bold; text-align:right">242,820</td>
<td style="font-weight: bold; text-align:right">2,973</td>
<td style="font-weight: bold; text-align:right">964,166,407</td>
<td style="font-weight: bold; text-align:right">2,884,272</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,284,143</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<td>4</td><td>336</td><td>0</td>
<td style="font-weight: bold; text-align:right">4</td>
<td style="font-weight: bold; text-align:right">0.08</td>
<td style="font-weight: bold; text-align:right">72,549</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">42,990,991</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">515,850 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">42,437,072</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">38,069</td>
<td style="font-weight: bold; text-align:right">8,944</td>
<td style="font-weight: bold; text-align:right">30,644</td>
<td style="font-weight: bold; text-align:right">368</td>
<td style="font-weight: bold; text-align:right">778,520,151</td>
<td style="font-weight: bold; text-align:right">554,921</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,402,939,494</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>33</td><td>2,720</td><td>2</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">27</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">29,350,379</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">654,993 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">27,671,593</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">1,023,793</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">136,441</td>
<td style="font-weight: bold; text-align:right">3,045</td>
<td style="font-weight: bold; text-align:right">63,776,166</td>
<td style="font-weight: bold; text-align:right">296,476</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,113,817</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>7</td><td>328</td><td>3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">4,759</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">23,514,144</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+60,422</td>
<td style="font-weight: bold; text-align:right;">140,109 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+29</td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">22,163,944</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+17,144</td>
<td style="text-align:right;font-weight:bold;">1,210,091</td>
<td style="font-weight: bold; text-align:right">1,928</td>
<td style="font-weight: bold; text-align:right">358,898</td>
<td style="font-weight: bold; text-align:right">2,138</td>
<td style="font-weight: bold; text-align:right">246,629,975</td>
<td style="font-weight: bold; text-align:right">3,764,325</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,517,712</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>3</td><td>468</td><td>0</td>
<td style="font-weight: bold; text-align:right">922</td>
<td style="font-weight: bold; text-align:right">0.4</td>
<td style="font-weight: bold; text-align:right">18,470</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">19,530,485</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">162,738 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">18,229,317</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">1,138,430</td>
<td style="font-weight: bold; text-align:right">253</td>
<td style="font-weight: bold; text-align:right">285,163</td>
<td style="font-weight: bold; text-align:right">2,376</td>
<td style="font-weight: bold; text-align:right">489,876,300</td>
<td style="font-weight: bold; text-align:right">7,152,637</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,488,908</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>4</td><td>421</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">16,622</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">17,335,186</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+44,989</td>
<td style="font-weight: bold; text-align:right;">360,811 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+596</td>
<td style="font-weight: bold; text-align:right">15,480,407</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+128,629</td>
<td style="text-align:right;font-weight:bold;">1,493,968</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">118,701</td>
<td style="font-weight: bold; text-align:right">2,471</td>
<td style="font-weight: bold; text-align:right">273,400,000</td>
<td style="font-weight: bold; text-align:right">1,872,086</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">146,040,262</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>8</td><td>405</td><td>1</td>
<td style="font-weight: bold; text-align:right">308</td>
<td style="font-weight: bold; text-align:right">4</td>
<td style="font-weight: bold; text-align:right">10,230</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">17,115,374</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+88,159</td>
<td style="font-weight: bold; text-align:right;">126,109 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+32</td>
<td style="font-weight: bold; text-align:right">13,349,900</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+76,200</td>
<td style="text-align:right;font-weight:bold;">3,639,365</td>
<td style="font-weight: bold; text-align:right">2,494</td>
<td style="font-weight: bold; text-align:right">203,181</td>
<td style="font-weight: bold; text-align:right">1,497</td>
<td style="font-weight: bold; text-align:right">104,701,826</td>
<td style="font-weight: bold; text-align:right">1,242,945</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">84,236,886</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>5</td><td>668</td><td>1</td>
<td style="font-weight: bold; text-align:right">1,047</td>
<td style="font-weight: bold; text-align:right">0.4</td>
<td style="font-weight: bold; text-align:right">43,204</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
<td style="font-weight: bold; text-align:right">14,551,665</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+17,426</td>
<td style="font-weight: bold; text-align:right;">96,487 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+138</td>
<td style="font-weight: bold; text-align:right">14,144,080</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+35,568</td>
<td style="text-align:right;font-weight:bold;">311,098</td>
<td style="font-weight: bold; text-align:right">975</td>
<td style="font-weight: bold; text-align:right">169,455</td>
<td style="font-weight: bold; text-align:right">1,124</td>
<td style="font-weight: bold; text-align:right">148,515,802</td>
<td style="font-weight: bold; text-align:right">1,729,479</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">85,873,124</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>6</td><td>890</td><td>1</td>
<td style="font-weight: bold; text-align:right">203</td>
<td style="font-weight: bold; text-align:right">2</td>
<td style="font-weight: bold; text-align:right">3,623</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">13,373,207</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+48,886</td>
<td style="font-weight: bold; text-align:right;">156,868 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+86</td>
<td style="font-weight: bold; text-align:right">12,216,835</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+36,111</td>
<td style="text-align:right;font-weight:bold;">999,504</td>
<td style="font-weight: bold; text-align:right">516</td>
<td style="font-weight: bold; text-align:right">221,736</td>
<td style="font-weight: bold; text-align:right">2,601</td>
<td style="font-weight: bold; text-align:right">192,560,616</td>
<td style="font-weight: bold; text-align:right">3,192,767</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,311,508</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>5</td><td>384</td><td>0</td>
<td style="font-weight: bold; text-align:right">811</td>
<td style="font-weight: bold; text-align:right">1</td>
<td style="font-weight: bold; text-align:right">16,572</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
<td style="font-weight: bold; text-align:right">11,223,974</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">101,135 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">10,294,394</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">828,445</td>
<td style="font-weight: bold; text-align:right">689</td>
<td style="font-weight: bold; text-align:right">239,903</td>
<td style="font-weight: bold; text-align:right">2,162</td>
<td style="font-weight: bold; text-align:right">471,036,328</td>
<td style="font-weight: bold; text-align:right">10,068,020</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,785,397</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>4</td><td>463</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">17,707</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/argentina/">Argentina</a></td>
<td style="font-weight: bold; text-align:right">8,970,196</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">127,122 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">8,769,953</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">73,121</td>
<td style="font-weight: bold; text-align:right">738</td>
<td style="font-weight: bold; text-align:right">195,442</td>

In [6]:
rows = table.find_all('tr')

In [7]:
rows[0].text.strip().split('\n')

['#',
 'Country,Other',
 'TotalCases',
 'NewCases',
 'TotalDeaths',
 'NewDeaths',
 'TotalRecovered',
 'NewRecovered',
 'ActiveCases',
 'Serious,Critical',
 'Tot\xa0Cases/1M pop',
 'Deaths/1M pop',
 'TotalTests',
 'Tests/',
 '1M pop',
 '',
 'Population',
 'Continent',
 '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl',
 'New Cases/1M pop',
 'New Deaths/1M pop',
 'Active Cases/1M pop']

In [8]:
data = []

for x in rows:
    data.append(x.text.strip().split('\n')[1:9])

df = pd.DataFrame(data)

df.head()

,0,1,2,3,4,5,6,7
0,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases
1,,"95,695,615","+10,080","1,425,823",+239,"68,721,845","+18,916","25,547,947"
2,,"126,010,670","+478,842","1,372,245","+1,205","112,418,352","+178,143","12,220,073"
3,,"55,223,002","+15,538","1,267,763",+95,"49,921,606","+40,891","4,033,633"
4,,"164,944,882","+384,229","1,738,979","+1,021","145,596,572","+484,992","17,609,331"

In [9]:
df=pd.DataFrame(data[9:],columns=data[0])

In [10]:
df.rename(columns={'Country,Other': 'Country', 'TotalCases': 'Total Cases','NewCases': 'New Cases','TotalDeaths': 'Total Deaths','NewDeaths': 'New Deaths','TotalRecovered': 'Total Recovered','NewRecovered': 'New Recovered','ActiveCases' : 'Active Cases'}, inplace=True)

In [15]:
df = df.set_index('Country')

,Total Cases,New Cases,Total Deaths,New Deaths,Total Recovered,New Recovered,Active Cases
Country,,,,,,,
USA,"81,171,036","+1,502","993,719",+26,"55,925,259","+10,121","24,252,058"
India,"42,990,991",,"515,850",,"42,437,072",,"38,069"
Brazil,"29,350,379",,"654,993",,"27,671,593",,"1,023,793"
France,"23,514,144","+60,422","140,109",+29,"22,163,944","+17,144","1,210,091"
UK,"19,530,485",,"162,738",,"18,229,317",,"1,138,430"
...,...,...,...,...,...,...,...
"164,944,882","+384,229","1,738,979","+1,021","145,596,572","+484,992","17,609,331","11,997"
"11,629,014",+423,"251,712",+15,"10,779,614","+1,804","597,688","1,555"
"4,211,709","+43,982","8,256",+24,"3,668,369","+23,589","535,084",159
721,,15,,706,,0,0
"457,715,613","+933,094","6,064,793","+2,599","391,107,064","+748,335","60,543,756","65,431"

In [12]:
df.to_csv('covid19.csv')